spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql=true
    show-sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./mydb;AUTO_SERVER=TRUE
    username: sa
    password: 123456
server:
  port: 8085