###get all books
GET localhost:8085/books

###get War and peace
GET localhost:8085/books/1

###update War and peace
PUT localhost:8085/books

{
    "id": 1,
    "name": "War and Peace222",
    "language": "Russian222",
    "category": "Novel222"
}

###add new book
POST localhost:8085/books

{
    "id": 4,
    "name": "Interesting book",
    "language": "Interesting language",
    "category": "super novel"
}

###delete a book
DELETE localhost:8085/books/2

###get all books
GET localhost:8085/books

